permissions:
  read_org:
    label: "View Organizations"
    can: [read, Organization]

  manage_orgs:
    label: "Manage Organizations"
    can: [manage, Organization]

  read_user_role:
    label: "View User Roles"
    can: [read, UserRole]

  manage_user_roles:
    label: "Manage User Roles"
    can: [manage, UserRole]

  read_user:
    label: "View Users"
    can: [read, OrgUser]

  manage_users:
    label: "Manage Users"
    can: [manage, OrgUser]

  manage_contents:
    label: "Manage Contents"
    can: [manage, Content]
